### ISSUE TITLE
这个是没有适配非Retina 显示屏吗？

### ISSUE THREAD

**Issue by superleeyom** [liuour/sogou#2]
请教一下，我用的是黑苹果，系统是macOS Big Sur，屏幕外接的是 1080p，为啥达不到你的这个效果呢？我这整体的效果感觉有点丑😂
![image](https://user-images.githubusercontent.com/22115219/109743917-6e7bf000-7c0c-11eb-83f1-9a399d9d9d0a.png)
盼回复 @liuour

**Comment by superleeyom** [comment]
我的搜狗版本号：
![image](https://user-images.githubusercontent.com/22115219/109744132-c4509800-7c0c-11eb-9f40-6286ed73073e.png)

**Comment by ssnhd** [comment]
白果正常，没有黑果无法复现

![截屏2021-03-03 下午2.25.41](https://tvax4.sinaimg.cn/large/008eZBHKgy1go6p76f4nrj319k04kq4g.jpg)

**Comment by superleeyom** [comment]
> 白果正常，没有黑果无法复现
> 
> ![截屏2021-03-03 下午2.25.41](https://camo.githubusercontent.com/0484adeff9341277f36f84ac2c67108011091969b2cd517abe0d5d24c976cbba/68747470733a2f2f74766178342e73696e61696d672e636e2f6c617267652f303038655a42484b677931676f3670373666346e726a3331396b30346b7134672e6a7067)

你的这个搜狗输入法的版本是多少呀？方便截图看看你皮肤设置页面吗？

**Comment by ssnhd** [comment]
版本 6.0.1.12387
![2021-03-03-14.46.53.@2x](https://tva3.sinaimg.cn/large/008eZBHKgy1go6ptufr9qj30vw0v441o.jpg)

**Comment by superleeyom** [comment]
![image](https://user-images.githubusercontent.com/22115219/109766013-94b38700-7c30-11eb-823a-79691109ade5.png)
![image](https://user-images.githubusercontent.com/22115219/109766076-aa28b100-7c30-11eb-9049-43a0b06f5218.png)
13像素圆角感觉在1080显示器上圆角太大了，感觉还是喜欢10像素，10像素的有打算多出几个配色没？

**Comment by ssnhd** [comment]
目前没这个计划，你可以在Photoshop里制作圆角更小的不同颜色的底图 → 然后搜狗皮肤管理器打开一个皮肤 → 载入底图 → 修改字体颜色等。

**Comment by superleeyom** [comment]
确实用retain显示器白果，整体的显示效果很好，在低分辨率的屏幕上，就不怎么好看了，圆角太大了，我就先关闭issue吧，谢谢了哈
![image](https://user-images.githubusercontent.com/22115219/109820486-ffd07e00-7c6f-11eb-9805-16f124de9fc1.png)

**Comment by superleeyom** [comment]
cool，你更新一个版本后，好看多了太感谢了，现在使用非常完美！
![image](https://user-images.githubusercontent.com/22115219/109970969-a67c5380-7d30-11eb-8741-c1421b63966e.png)
![image](https://user-images.githubusercontent.com/22115219/109971007-b431d900-7d30-11eb-9b9d-e55cf31c8ca6.png)

**Comment by ssnhd** [comment]
所有皮肤都更新，圆角缩小为8像素，之前是10和13像素。
其次在非Retina屏幕下显示仍然会放大圆角，这个无法改变。

**Comment by superleeyom** [comment]
> 所有皮肤都更新，圆角缩小为8像素，之前是10和13像素。
> 其次在非Retina屏幕下显示仍然会放大圆角，这个无法改变。

已经挺好的了，感谢！！！
