### ISSUE TITLE
付费帮忙定制

### ISSUE THREAD

**Issue by iyoung69** [liuour/sogou#4]
你好，我在v2ex 上面看到了关于你的皮肤的帖子，看了你制作的皮肤之后非常喜欢，使用了你制作的皮肤之后发现了一个问题，单方模式最后面的上下箭头与字体的间距太小了，这是我的看法不知道你有没有发现，我还有一个想法，就是我想付费100 元，请你帮忙修改一下你的白底蓝字的这个皮肤，修改成
https://github.com/maomiui/rime
rime 这种蓝白的皮肤，如果你有兴趣，这是我的联系方式：eWFuZ2ZlaXhpYW5nNjlAZ21haWwuY29t

**Comment by ssnhd** [comment]
箭头与字体间距如果太大，卷轴模式时右侧会出现很大空白区域不美观。

目前皮肤不支持制作成类 macOS UI

**Comment by iyoung69** [comment]
好吧，明白了，感谢百忙之中回复我的消息
