### ISSUE TITLE
增加win版本的皮肤

### ISSUE THREAD

**Issue by sunnyday2006** [liuour/sogou#5]
你好，皮肤很喜欢。是否可以增加适配win版本的ssf皮肤？

**Comment by ssnhd** [comment]
不好意思，身边没有 Windows 设备，且 Win 版不支持卷轴模式，故目前没办法增加。

**Comment by sunnyday2006** [comment]
感谢回复。有没有其他方式可以把皮肤mssf转换成ssf？

**Comment by ssnhd** [comment]
好像没有。
